/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as OmOssRouteImport } from './routes/om-oss'
import { Route as RestaureringRouteImport } from './routes/restaurering'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SkickaInSkorRouteImport } from './routes/skicka-in-skor'
import { Route as VarukorgRouteImport } from './routes/varukorg'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ProduktIdRouteImport } from './routes/produkt.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const OmOssRoute = OmOssRouteImport.update({
  id: '/om-oss',
  path: '/om-oss',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaureringRoute = RestaureringRouteImport.update({
  id: '/restaurering',
  path: '/restaurering',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SkickaInSkorRoute = SkickaInSkorRouteImport.update({
  id: '/skicka-in-skor',
  path: '/skicka-in-skor',
  getParentRoute: () => rootRouteImport,
} as any)
const VarukorgRoute = VarukorgRouteImport.update({
  id: '/varukorg',
  path: '/varukorg',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduktIdRoute = ProduktIdRouteImport.update({
  id: '/produkt/$id',
  path: '/produkt/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/kontakt': typeof KontaktRoute
  '/om-oss': typeof OmOssRoute
  '/restaurering': typeof RestaureringRoute
  '/shop': typeof ShopRoute
  '/skicka-in-skor': typeof SkickaInSkorRoute
  '/varukorg': typeof VarukorgRoute
  '/api/chat': typeof ApiChatRoute
  '/produkt/$id': typeof ProduktIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/kontakt': typeof KontaktRoute
  '/om-oss': typeof OmOssRoute
  '/restaurering': typeof RestaureringRoute
  '/shop': typeof ShopRoute
  '/skicka-in-skor': typeof SkickaInSkorRoute
  '/varukorg': typeof VarukorgRoute
  '/api/chat': typeof ApiChatRoute
  '/produkt/$id': typeof ProduktIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/kontakt': typeof KontaktRoute
  '/om-oss': typeof OmOssRoute
  '/restaurering': typeof RestaureringRoute
  '/shop': typeof ShopRoute
  '/skicka-in-skor': typeof SkickaInSkorRoute
  '/varukorg': typeof VarukorgRoute
  '/api/chat': typeof ApiChatRoute
  '/produkt/$id': typeof ProduktIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/kontakt'
    | '/om-oss'
    | '/restaurering'
    | '/shop'
    | '/skicka-in-skor'
    | '/varukorg'
    | '/api/chat'
    | '/produkt/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/kontakt'
    | '/om-oss'
    | '/restaurering'
    | '/shop'
    | '/skicka-in-skor'
    | '/varukorg'
    | '/api/chat'
    | '/produkt/$id'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/kontakt'
    | '/om-oss'
    | '/restaurering'
    | '/shop'
    | '/skicka-in-skor'
    | '/varukorg'
    | '/api/chat'
    | '/produkt/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  KontaktRoute: typeof KontaktRoute
  OmOssRoute: typeof OmOssRoute
  RestaureringRoute: typeof RestaureringRoute
  ShopRoute: typeof ShopRoute
  SkickaInSkorRoute: typeof SkickaInSkorRoute
  VarukorgRoute: typeof VarukorgRoute
  ApiChatRoute: typeof ApiChatRoute
  ProduktIdRoute: typeof ProduktIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om-oss': {
      id: '/om-oss'
      path: '/om-oss'
      fullPath: '/om-oss'
      preLoaderRoute: typeof OmOssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurering': {
      id: '/restaurering'
      path: '/restaurering'
      fullPath: '/restaurering'
      preLoaderRoute: typeof RestaureringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skicka-in-skor': {
      id: '/skicka-in-skor'
      path: '/skicka-in-skor'
      fullPath: '/skicka-in-skor'
      preLoaderRoute: typeof SkickaInSkorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/varukorg': {
      id: '/varukorg'
      path: '/varukorg'
      fullPath: '/varukorg'
      preLoaderRoute: typeof VarukorgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produkt/$id': {
      id: '/produkt/$id'
      path: '/produkt/$id'
      fullPath: '/produkt/$id'
      preLoaderRoute: typeof ProduktIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  KontaktRoute: KontaktRoute,
  OmOssRoute: OmOssRoute,
  RestaureringRoute: RestaureringRoute,
  ShopRoute: ShopRoute,
  SkickaInSkorRoute: SkickaInSkorRoute,
  VarukorgRoute: VarukorgRoute,
  ApiChatRoute: ApiChatRoute,
  ProduktIdRoute: ProduktIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
